#!/usr/bin/env fish

if [ "$argv[1]" = "-v" ] || [ "$argv[1]" = "--version" ];
  echo 'UnityX 10.0-rc5' && exit
end

# Change directory to unityx directory
cd (dirname (status -f))

# Source core lib
source core/lib.fish

# Set XDG_CURRENT_DESKTOP
export XDG_CURRENT_DESKTOP=UnityX

# Start unityx-settings-daemon
load settings_daemon
