#!/usr/bin/env fish

# Check if Xephyr is installed
which Xephyr &>/dev/null || echo 'Xephyr is not installed on this machine. Quitting.' >&2

# Launch UnityX window
Xephyr -br :4 -screen 1600x900 &
sleep 1
[ -f "./unityx" ] && set PREFIX './'
DISPLAY=:4 "$PREFIX"unityx || DISPLAY=:4 /usr/share/unityx/unityx
wait
